version: '3.7'
# TO DO: add certbot
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: always
    volumes:
      - ./docker/nginx/conf:/etc/letsencrypt
    env_file: .env
    links:
      - web
    ports:
      - 80:80
      - 443:443

  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    restart: always
    volumes:
      - redis-data:/data
    env_file: .env

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    restart: always
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./:/home/dockeruser/project
      - backend-modules:/usr/local/bundle
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - redis
    links:
      - redis

volumes:
  backend-modules:
  redis-data:
